# Generated by Django 2.0.2 on 2018-03-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sequncer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_number', models.IntegerField(verbose_name='Sample_Number')),
                ('sequencer', models.CharField(max_length=100, verbose_name='Sequencer')),
            ],
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_number', models.IntegerField(verbose_name='Sample_Number')),
                ('cdna_variant', models.CharField(max_length=200, verbose_name='cDNA_change')),
                ('protein_variant', models.CharField(max_length=200, verbose_name='Protein_change')),
                ('genome_variant', models.CharField(max_length=200, verbose_name='Genome_change')),
            ],
        ),
    ]
