# Generated by Django 2.0.2 on 2018-03-02 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sequncer',
            new_name='Sequencer',
        ),
    ]
