# Generated by Django 2.0.2 on 2018-03-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raw_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_number', models.IntegerField(verbose_name='Sample_Number')),
                ('first_name', models.CharField(max_length=100, verbose_name='First_Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last_Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('stage', models.IntegerField(verbose_name='Stage')),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
                ('sequencer', models.CharField(max_length=100, verbose_name='Sequencer')),
                ('cDNA_variant', models.CharField(max_length=200, verbose_name='cDNA_change')),
                ('protein_variant', models.CharField(max_length=200, verbose_name='Protein_change')),
                ('genomic_variant', models.CharField(max_length=200, verbose_name='Genome_change')),
            ],
        ),
    ]
