# Generated by Django 2.0.2 on 2018-03-01 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Raw_data',
            new_name='Sample',
        ),
    ]
