# Generated by Django 2.0.2 on 2018-03-01 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20180301_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='genomic_variant',
            new_name='genome_variant',
        ),
    ]
