# Generated by Django 2.0.2 on 2018-03-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='text_attri',
        ),
    ]
