# Generated by Django 2.0.2 on 2018-03-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_remove_test_text_attri'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='text_attri',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
