# Generated by Django 2.0.2 on 2018-03-01 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20180301_1431'),
        ('data', '0004_remove_test_text_attri'),
    ]

    operations = [
    ]
