# Generated by Django 2.0.2 on 2018-03-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_merge_20180301_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='number_attri',
            field=models.IntegerField(default=0),
        ),
    ]
