# Generated by Django 2.0.2 on 2018-03-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_test_text_attri'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='number_attri',
            field=models.IntegerField(default='', verbose_name=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='text_attri',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
    ]
