# Generated by Django 2.0.2 on 2018-03-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20180301_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='number_attri',
            field=models.IntegerField(default=0),
        ),
    ]
