# Generated by Django 2.0.2 on 2018-03-01 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
    ]
