# Generated by Django 2.0.2 on 2018-03-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20180301_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='number_attri',
        ),
    ]
