# Generated by Django 2.0.2 on 2018-03-01 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_test_number_attri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='number_attri',
        ),
    ]
