# Generated by Django 2.0.2 on 2018-03-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_remove_test_number_attri'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='number_attri',
            field=models.IntegerField(default=0),
        ),
    ]
