# Generated by Django 2.0.2 on 2018-03-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_test_number_attri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='text_attri',
            field=models.CharField(max_length=100),
        ),
    ]
